//! `.loy` format: the AST (`Program`) plus any embedded wasm modules, serialized
//! into a platform-independent binary artifact — "compile once, run on any
//! `alloy`".
//!
//! Layout: `magic(8)` + `fmt_ver: u16 LE` + bincode(`alloy_ver: String`) +
//! bincode(payload). For `fmt_ver == 1` the payload is just `Vec<Item>` (legacy,
//! still loadable). For `fmt_ver >= 2` it is a [`Payload`] = `Vec<Item>` +
//! `Vec<WasmModule>`: the AST stays interpreted; the wasm carries imported Rust
//! (`.rs`) compiled to `wasm32`, so the artifact is self-contained and needs no
//! rustc to run. Data only (no native code) → the same file runs everywhere.

use copper_syntax::program::{Item, Program};
use serde::{Deserialize, Serialize};

pub const MAGIC: &[u8; 8] = b"ALLOYBC\0";
/// Format version. v1 = AST only; v2 = AST + embedded wasm modules. Increment
/// when the AST shape or payload changes in an incompatible way.
pub const FMT_VERSION: u16 = 2;

const ALLOY_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Imported Rust (`.rs`) compiled to wasm and embedded in the `.loy`. `names`
/// are the exported symbols this module provides (the imported function names).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WasmModule {
    pub names: Vec<String>,
    pub bytes: Vec<u8>,
}

/// The v2 `.loy` payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
struct Payload {
    items: Vec<Item>,
    wasm: Vec<WasmModule>,
}

/// Serializes a `Program`'s items + embedded wasm modules into `.loy` bytes.
pub fn compile(items: &[Item], wasm: &[WasmModule]) -> Vec<u8> {
    let mut out = Vec::new();
    out.extend_from_slice(MAGIC);
    out.extend_from_slice(&FMT_VERSION.to_le_bytes());
    let ver = bincode::serialize(ALLOY_VERSION).unwrap_or_default();
    out.extend_from_slice(&ver);
    let payload = Payload {
        items: items.to_vec(),
        wasm: wasm.to_vec(),
    };
    let body = bincode::serialize(&payload).unwrap_or_default();
    out.extend_from_slice(&body);
    out
}

/// `true` if the bytes start with the `.loy` format magic.
pub fn is_bytecode(bytes: &[u8]) -> bool {
    bytes.len() >= 8 && &bytes[..8] == MAGIC
}

/// Verifies the magic + version and deserializes the program + embedded wasm.
/// Never panics: returns `Err` with a clear message on any inconsistency.
pub fn load(bytes: &[u8]) -> Result<(Program, Vec<WasmModule>), String> {
    if !is_bytecode(bytes) {
        return Err("invalid .loy file (magic missing)".into());
    }
    if bytes.len() < 10 {
        return Err("truncated .loy file".into());
    }
    let ver = u16::from_le_bytes([bytes[8], bytes[9]]);
    if ver == 0 || ver > FMT_VERSION {
        return Err(format!(
            "artifact generated by a newer Alloy (format v{ver}, runtime supports up to v{FMT_VERSION})"
        ));
    }
    let mut rest = &bytes[10..];
    // skip the generator version string.
    let _gen_ver: String =
        bincode_take(&mut rest).map_err(|e| format!("corrupted artifact: {e}"))?;
    let (items, wasm) = if ver == 1 {
        // Legacy: payload is just Vec<Item>.
        let items: Vec<Item> =
            bincode::deserialize(rest).map_err(|e| format!("corrupted artifact: {e}"))?;
        (items, Vec::new())
    } else {
        let payload: Payload =
            bincode::deserialize(rest).map_err(|e| format!("corrupted artifact: {e}"))?;
        (payload.items, payload.wasm)
    };
    Ok((
        Program {
            items,
            errors: Vec::new(),
        },
        wasm,
    ))
}

/// Deserializes a value from the start of `buf` and advances `buf` past it.
fn bincode_take<T: serde::de::DeserializeOwned + serde::Serialize>(
    buf: &mut &[u8],
) -> Result<T, bincode::Error> {
    use bincode::Options;
    // Measure how much was consumed by re-serializing the read value (bincode 1
    // doesn't expose the cursor directly; the default config is deterministic).
    let opts = bincode::options()
        .with_fixint_encoding()
        .allow_trailing_bytes();
    let value: T = opts.deserialize(buf)?;
    let consumed = bincode::options()
        .with_fixint_encoding()
        .serialized_size(&value)? as usize;
    *buf = &buf[consumed..];
    Ok(value)
}

#[cfg(test)]
mod tests {
    use super::*;
    use copper_syntax::program::parse_program;

    #[test]
    fn round_trip() {
        let prog = parse_program("func int add(a: int, b: int) { return a + b }\nadd(2, 3)\n");
        let bytes = compile(&prog.items, &[]);
        assert!(is_bytecode(&bytes));
        let (loaded, wasm) = load(&bytes).expect("load ok");
        assert_eq!(loaded.items.len(), prog.items.len());
        assert!(wasm.is_empty());
    }

    #[test]
    fn round_trip_with_wasm() {
        let prog = parse_program("func main() {}\n");
        let modules = vec![WasmModule {
            names: vec!["add".into()],
            bytes: vec![0, 1, 2, 3],
        }];
        let bytes = compile(&prog.items, &modules);
        let (_, wasm) = load(&bytes).expect("load ok");
        assert_eq!(wasm.len(), 1);
        assert_eq!(wasm[0].names, vec!["add".to_string()]);
        assert_eq!(wasm[0].bytes, vec![0, 1, 2, 3]);
    }

    #[test]
    fn rejects_garbage_and_bad_version() {
        assert!(!is_bytecode(b"not bytecode"));
        assert!(load(b"not bytecode at all").is_err());
        let mut bytes = compile(&[], &[]);
        bytes[8] = 99; // corrupt the version
        assert!(load(&bytes).is_err());
    }
}
