//! `.loy` format: the AST (`Program`) serialized into a platform-independent
//! binary artifact — "compile once, run on any `alloy`".
//!
//! Layout: `magic(8)` + `fmt_ver: u16 LE` + bincode(`alloy_ver: String`) +
//! bincode(`items: Vec<Item>`). Data only (no native code), so the same
//! file runs on Windows/macOS/Linux.

use copper_syntax::program::{Item, Program};

pub const MAGIC: &[u8; 8] = b"ALLOYBC\0";
/// Format version. Increment when the AST shape changes in an incompatible
/// way (new fields/variants that break deserialization).
pub const FMT_VERSION: u16 = 1;

const ALLOY_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Serializa os itens de um `Program` em bytes `.loy`.
pub fn compile(items: &[Item]) -> Vec<u8> {
    let mut out = Vec::new();
    out.extend_from_slice(MAGIC);
    out.extend_from_slice(&FMT_VERSION.to_le_bytes());
    // generator version (informative) + items.
    let ver = bincode::serialize(ALLOY_VERSION).unwrap_or_default();
    out.extend_from_slice(&ver);
    let body = bincode::serialize(items).unwrap_or_default();
    out.extend_from_slice(&body);
    out
}

/// `true` if the bytes start with the `.loy` format magic.
pub fn is_bytecode(bytes: &[u8]) -> bool {
    bytes.len() >= 8 && &bytes[..8] == MAGIC
}

/// Verifies the magic + version and deserializes the `Program`. Never panics:
/// returns `Err` with a clear message on any inconsistency.
pub fn load(bytes: &[u8]) -> Result<Program, String> {
    if !is_bytecode(bytes) {
        return Err("invalid .loy file (magic missing)".into());
    }
    if bytes.len() < 10 {
        return Err("truncated .loy file".into());
    }
    let ver = u16::from_le_bytes([bytes[8], bytes[9]]);
    if ver != FMT_VERSION {
        return Err(format!(
            "artifact generated by a different Alloy version (format v{ver}, runtime expects v{FMT_VERSION})"
        ));
    }
    let mut rest = &bytes[10..];
    // skip the generator version string.
    let _gen_ver: String =
        bincode_take(&mut rest).map_err(|e| format!("corrupted artifact: {e}"))?;
    let items: Vec<Item> =
        bincode::deserialize(rest).map_err(|e| format!("corrupted artifact: {e}"))?;
    Ok(Program {
        items,
        errors: Vec::new(),
    })
}

/// Deserializes a value from the start of `buf` and advances `buf` past it.
fn bincode_take<T: serde::de::DeserializeOwned + serde::Serialize>(
    buf: &mut &[u8],
) -> Result<T, bincode::Error> {
    use bincode::Options;
    // Measure how much was consumed by re-serializing the read value (bincode 1
    // doesn't expose the cursor directly; the default config is deterministic).
    let opts = bincode::options()
        .with_fixint_encoding()
        .allow_trailing_bytes();
    let value: T = opts.deserialize(buf)?;
    let consumed = bincode::options()
        .with_fixint_encoding()
        .serialized_size(&value)? as usize;
    *buf = &buf[consumed..];
    Ok(value)
}

#[cfg(test)]
mod tests {
    use super::*;
    use copper_syntax::program::parse_program;

    #[test]
    fn round_trip() {
        let prog = parse_program("func int add(a: int, b: int) { return a + b }\nadd(2, 3)\n");
        let bytes = compile(&prog.items);
        assert!(is_bytecode(&bytes));
        let loaded = load(&bytes).expect("load ok");
        assert_eq!(loaded.items.len(), prog.items.len());
    }

    #[test]
    fn rejects_garbage_and_bad_version() {
        assert!(!is_bytecode(b"not bytecode"));
        assert!(load(b"not bytecode at all").is_err());
        let mut bytes = compile(&[]);
        bytes[8] = 99; // corrupt the version
        assert!(load(&bytes).is_err());
    }
}
