// `reflect` module — runtime reflection over Copper structs, std-only.
// Bundled into `pub mod reflect { ... }` alongside std/reflect.crs.
//
// cforge auto-generates `impl reflect::Reflect for <Struct>` for every Copper
// struct in the program when this module is imported.

use std::fmt;

/// A reflected field value. Copper scalars and string lists map directly.
#[derive(Clone, Debug, PartialEq)]
pub enum Value {
    Int(i64),
    Float(f64),
    Bool(bool),
    Str(String),
    List(Vec<Value>),
    Null,
}

impl Value {
    /// Human-readable rendering.
    pub fn show(&self) -> String {
        match self {
            Value::Int(n) => n.to_string(),
            Value::Float(f) => f.to_string(),
            Value::Bool(b) => b.to_string(),
            Value::Str(s) => s.clone(),
            Value::List(xs) => {
                let parts: Vec<String> = xs.iter().map(|v| v.show()).collect();
                format!("[{}]", parts.join(", "))
            }
            Value::Null => "null".to_string(),
        }
    }
}

impl fmt::Display for Value {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.show())
    }
}

impl From<i64> for Value { fn from(v: i64) -> Self { Value::Int(v) } }
impl From<i32> for Value { fn from(v: i32) -> Self { Value::Int(v as i64) } }
impl From<f64> for Value { fn from(v: f64) -> Self { Value::Float(v) } }
impl From<f32> for Value { fn from(v: f32) -> Self { Value::Float(v as f64) } }
impl From<bool> for Value { fn from(v: bool) -> Self { Value::Bool(v) } }
impl From<String> for Value { fn from(v: String) -> Self { Value::Str(v) } }
impl From<&str> for Value { fn from(v: &str) -> Self { Value::Str(v.to_string()) } }
impl<T: Into<Value>> From<Vec<T>> for Value {
    fn from(v: Vec<T>) -> Self {
        Value::List(v.into_iter().map(Into::into).collect())
    }
}

/// The reflected view of a value: its type name and ordered (name, value) fields.
#[derive(Clone, Debug)]
pub struct Reflected {
    type_name: String,
    fields: Vec<(String, Value)>,
}

impl Reflected {
    pub fn new(type_name: &str, fields: Vec<(String, Value)>) -> Self {
        Reflected { type_name: type_name.to_string(), fields }
    }
    pub fn type_name(&self) -> String { self.type_name.clone() }
    pub fn keys(&self) -> Vec<String> {
        self.fields.iter().map(|(k, _)| k.clone()).collect()
    }
    pub fn values(&self) -> Vec<Value> {
        self.fields.iter().map(|(_, v)| v.clone()).collect()
    }
    pub fn fields(&self) -> Vec<(String, Value)> { self.fields.clone() }
    pub fn get(&self, name: &str) -> Option<Value> {
        self.fields.iter().find(|(k, _)| k == name).map(|(_, v)| v.clone())
    }
    pub fn has(&self, name: &str) -> bool {
        self.fields.iter().any(|(k, _)| k == name)
    }
    pub fn len(&self) -> i64 { self.fields.len() as i64 }
    pub fn is_empty(&self) -> bool { self.fields.is_empty() }
}

/// Implemented (auto-generated by cforge) for every Copper struct when the
/// `reflect` module is imported.
pub trait Reflect {
    fn reflect(&self) -> Reflected;
}

/// Reflect any value implementing `Reflect`: `reflect::of(&obj)`.
pub fn of<T: Reflect>(value: &T) -> Reflected { value.reflect() }
